### ISSUE TITLE
Can't install APK

### ISSUE THREAD

**Issue by USLTD** [BlazeCodeDev/EventTool#1]
**Describe the bug**
When trying to install via **SAI** (Split Apks Installer which also features errors), it says that Android version on my device (Android 11) is lower than minimal version required by package.

**To Reproduce**
1. Download any version from [releases](https://github.com/BlazeCodeDev/EventTool/releases)
2. Try installing it on Android 11. Recommended to use SAI
3. See error

**Expected behavior**
For installation to finish successfully

**Screenshots**
![Screenshot_2022-11-28-09-03-11-573_com aefyr sai](https://user-images.githubusercontent.com/57063715/204198217-65fde25e-2d2d-4ec1-821e-1d700bb5067a.jpg)

![Screenshot_2022-11-28-08-56-40-222_com aefyr sai](https://user-images.githubusercontent.com/57063715/204197216-c9ece6d5-9370-4e70-b96a-1981b7b0df60.jpg)

**Smartphone (please complete the following information):**
 - Device: **Xiaomi Redmi Note 8 Pro Begonia Global Europe ROM**
 - OS: **MIUI 12.5/Android 11**
 - Version **ANY**

**Additional context**
*NOTHING*

**Comment by USLTD** [comment]
I think this is culprit
![IMG_20221128_091032](https://user-images.githubusercontent.com/57063715/204198729-1baeeff8-2c5e-4b6d-929b-cf351b0dfee4.jpg)

**Comment by BlazeCodeDev** [comment]
That indeed is the culprit. Currently the required minimum Android version is 13. I'm using some functions that require A13. I'm not planning on refactoring that anytime soon though.

**Comment by USLTD** [comment]
Can you tell me which are Android 13 specific functions?

**Comment by BlazeCodeDev** [comment]
MainActivity line 48: 
```
extras?.getParcelable()
```

**Comment by USLTD** [comment]
Thanks
